'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class main

    '''<summary>
    '''accountAnalysis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accountAnalysis As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblIncomeAnalysis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIncomeAnalysis As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdAccountAnalysis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAccountAnalysis As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdCdsAccountAnalysis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCdsAccountAnalysis As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdWebUserEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdWebUserEvents As Global.System.Web.UI.WebControls.GridView
End Class
