'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class statistics

    '''<summary>
    '''lblResumeQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResumeQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResumeUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResumeUS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblincomesQue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblincomesQue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblexpensesQue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblexpensesQue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblincomesDol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblincomesDol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblexpensesdol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblexpensesdol As Global.System.Web.UI.WebControls.Label
End Class
